FROM python:3.13-slim
RUN apt-get update -qy \
 && apt-get -qy install \
    build-essential \
    g++ \
    git \
    wget \
 && rm -rf /var/lib/apt/lists/* \
 && pip install --upgrade uv

ENV PYTHONUNBUFFERED=0
ENV PROJECT=gitui2
WORKDIR /src/$PROJECT
